### ISSUE TITLE
Fabric not located? [1.16.5]

### ISSUE THREAD

**Issue by ronneycz** [5zig-reborn/deployments#8]
For some reason upon starting Minecraft 1.16.5 with Fabric the game doesn't manage to launch. Fabric is installed successfully, the game starts up with Fabric when only Sodium mod is active. Sodium and 5zig don't collide, I tested that. I'm enclosing the error window picture and log. I'm using Arch Linux and multimc5 Minecraft launcher if that matters at all.

![2021_04_09-21_51_26](https://user-images.githubusercontent.com/40179235/114234195-bb2ab780-997e-11eb-8d30-34f4941925ba.png)

```
MultiMC version: 0.6.12-custom


Minecraft folder is:
/home/roman/.local/share/multimc/instances/1.16.5/.minecraft


Java path is:
/usr/lib/jvm/java-8-openjdk/bin/java


Checking Java version...
Java is version 1.8.0_282, using 64-bit architecture, from Oracle Corporation.


AMD Ryzen 5 2600X Six-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)

Subsystem: Sapphire Technology Limited Nitro+ Radeon RX 570/580/590

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.1

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /home/roman/.local/share/multimc/instances/1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/roman/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/roman/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/roman/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/roman/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /home/roman/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/roman/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/roman/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/roman/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/roman/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/roman/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/roman/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /home/roman/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/roman/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/roman/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/roman/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/roman/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/roman/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/roman/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /home/roman/.local/share/multimc/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /home/roman/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /home/roman/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /home/roman/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /home/roman/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /home/roman/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /home/roman/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.11.3/fabric-loader-0.11.3.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/roman/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [✔️] 5zig-Reborn-1.16.1-b251
  [✔️] sodium-fabric-mc1.16.3-0.1.0

Params:
  --username  --version MultiMC5 --gameDir /home/roman/.local/share/multimc/instances/1.16.5/.minecraft --assetsDir /home/roman/.local/share/multimc/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms2048m, -Xmx6144m, -Duser.language=en]


Wrapper command is:
mangohud --dlsym


Minecraft process ID: 68132


Using onesix launcher.

[21:34:14] [main/INFO]: Loading for game Minecraft 1.16.5
[21:34:14] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'the5zigmod' (the5zigmod) requires any version of mod fabric, which is missing!
	 - You must install any version of fabric.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:322) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by UltraBlackLinux** [comment]
1. There is formatting
2. Fabric __Mod__ == Fabric api - makes sense, huh?
Think please.

**Comment by ronneycz** [comment]
Alright, I figured out the formatting now.

I'm afraid I don't understand your second point, I would like to but my technical capabilities don't seem to be good enough. I have Fabric mod loader installed yet Sodium doesn't find it.

**Comment by UltraBlackLinux** [comment]
> Alright, I figured out the formatting now.
> 
> I'm afraid I don't understand your second point, I would like to but my technical capabilities don't seem to be good enough. I have Fabric mod loader installed yet Sodium doesn't find it.

bruh.
Fabric heavily relies on it's api.
https://www.curseforge.com/minecraft/mc-mods/fabric-api
Why does nobody ever understand that?!

**Comment by ronneycz** [comment]
I see, thank you man, I'm a casual player and I had no idea. Works like a charm now.
